hidden_size: 100
no_block_embedding: false
k_neighbors: 9
mode: Test
conv_name: EGNN
lr: 0.0001
lr_l: 0.001
epoch_pre: 30
epoch: 2000
train_rate: 0.8
batch_size: 40
class_num: 2
start_epoch: 0
end_epoch: 20
T: 0.5
num_k: 1000
n_layers: 1
w_consistent: 0.0
w_ent: 0.0
margin: 0.4
select_pocket_war: 10
select_pocket_e3: 10
e3_dim: 30
tar_dim: 30
protac_dim: 167
attention: false
seed: 111
dataset_type: name_regression_trainable
feature: true
